name: flutter_socket_plugin
description: FlutterSocket is a practical cross-platform socket plugin,supports both iOS and Android.
version: 1.0.1
homepage: https://github.com/waitwalker/flutter_socket_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cn.waitwalker.flutter_socket_plugin
    pluginClass: FlutterSocketPlugin