name: flutter_socket_plugin
description: FlutterSocket is a practical cross-platform socket plugin,supports both iOS and Android.
version: 3.0.0
homepage: https://github.com/waitwalker/flutter_socket_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: cn.waitwalker.flutter_socket_plugin
        pluginClass: FlutterSocketPlugin
      ios:
        pluginClass: FlutterSocketPlugin